[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
location-guessing-game-telegram-bot = {path = ".", editable = true}

[dev-packages]
black = "*"
mypy = "*"
pylint = "*"
pylint-import-requirements = "*"
pytest = "*"
pytest-cov = "*"

# python3.10 compatibility
# >   File "[...]/lib/python3.10/site-packages/mypy/main.py", line 11, in <module>
# >     from typing_extensions import Final, NoReturn
# > ModuleNotFoundError: No module named 'typing_extensions'
typing_extensions = {version = "*", markers = ""}
# mypy on python<3.8
typed-ast = {markers = "python_version < '3.8'"}
# python<=3.8 compatibility
# > [...]/python3.8/site-packages/telegram/ext/jobqueue.py:27: in <module>
# >     from apscheduler.schedulers.background import BackgroundScheduler
# > [...]
# > [...]/python3.8/site-packages/tzlocal/unix.py:6: in <module>
# >     import pytz_deprecation_shim as pds
# > [...]
# > [...]/python3.8/site-packages/pytz_deprecation_shim/_compat_py3.py:7: in <module>
# >     from backports import zoneinfo
# > E   ModuleNotFoundError: No module named 'backports'
# > Error: Process completed with exit code 4.
"backports.zoneinfo" = {version = "*", markers = "python_version <= '3.8'"}
# >    File "[...]/lib/python3.10/site-packages/_pytest/_code/code.py", line 60, in <module>
# >     from exceptiongroup import BaseExceptionGroup
# > ModuleNotFoundError: No module named 'exceptiongroup'
exceptiongroup = {markers = "python_version < '3.11'"}
# >   File "[...]/lib/python3.10/site-packages/_pytest/config/findpaths.py", line 71, in load_config_dict_from_file
# >     import tomli as tomllib
# > ModuleNotFoundError: No module named 'tomli'
tomli = {markers = "python_version < '3.11'"}
# >   File "[...]/lib/python3.10/site-packages/astroid/decorators.py", line 16, in <module>
# >     import wrapt
# > ModuleNotFoundError: No module named 'wrapt'
wrapt = "*"

[requires]
python_version = "3"

# Pipfile syntax: https://github.com/pypa/pipfile#pipfile
